### ISSUE TITLE
clusterhq/homebrew-tap/*.rb sha1 is deprecated

### ISSUE THREAD

**Issue by denji** [ClusterHQ/homebrew-tap#30]
Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
…/Library/Taps/clusterhq/homebrew-tap/flocker-0.3.2.rb:16:in `block in class:Flocker032'
Please report this to the clusterhq/tap tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
…/Library/Taps/clusterhq/homebrew-tap/flocker-0.3.2.rb:16:in `block in class:Flocker032'
Please report this to the clusterhq/tap tap!

**Comment by reppolice** [comment]
Not entirely sure why this was closed, but the warning since to be an error now, and pretty much has "broken" my brew, is the SHA256 fix in the mix?

**brew install golang libjpeg-turbo
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/clusterhq/homebrew-flocker/flocker-0.4.0.rb:6:in `<class:Flocker040>'
Please report this to the clusterhq/flocker tap!**

**Comment by denji** [comment]
> Not entirely sure why this was closed

`brew untap ClusterHQ/tap` just don't seem to use anymore.

**Comment by wallrj** [comment]
Sorry for the bad communication.

We abandoned the Homebrew installation script in favour of ``virtualenv`` and `pip install`...which is less error prone and easier for us to support.

https://flocker-docs.clusterhq.com/en/latest/flocker-standalone/install-client.html#installing-on-os-x

Thanks @denji for mentioning the `brew untap ClusterHQ/tap`  command.
